# .pre-commit-config.yaml
repos:
-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.1.1 # This is a specific, stable version
    hooks:
    -   id: conventional-pre-commit
        stages: [commit-msg]